name: VSCode + Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Lock to the version shipped with VSCode 1.43+
        node-version: ['12.8.1']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: npm ci
      - run: npm run prettier -- --list-different
      - run: npm run compile
      - run: npm run lint
      - run: npm audit
      # Ensure we run our tests with a display set for Linux (not provided by default)
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'

  # https://forge.rust-lang.org/infra/docs/bors.html#adding-a-new-repository-to-bors
  build_result:
    name: bors build finished
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
